#!/bin/bash
# Stage Pi: Open source stagebox firmware
# Copyright (C) 2025 Bama Box ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.

# This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

set -e

echo "Post-install script running..."

# Source directory inside the package
SOURCE_DIR="/usr/local/stagepi/installer-files"

# Install AES scripts
install -m 755 "$SOURCE_DIR/scripts/AES67-3ms-eth-rx" /usr/local/bin/
install -m 755 "$SOURCE_DIR/scripts/AES67-10ms-wifi-rx" /usr/local/bin/
install -m 755 "$SOURCE_DIR/scripts/stream-eth.sh" /usr/local/bin/
install -m 755 "$SOURCE_DIR/scripts/stream-wifi.sh" /usr/local/bin/

# Copy configuration files and directories to /etc
install -d /etc/linuxptp
install -m 644 "$SOURCE_DIR/etc/linuxptp/ptp4l.conf" /etc/linuxptp/
install -d /etc/bluetooth
install -m 644 "$SOURCE_DIR/etc/bluetooth/main.conf" /etc/bluetooth/
install -m 644 "$SOURCE_DIR/etc/shairport-sync.conf" /etc/

# Copy systemd service files
install -d /etc/systemd/system
install -m 644 "$SOURCE_DIR/etc/systemd/system/stagepi-ble.service" /etc/systemd/system/
install -m 644 "$SOURCE_DIR/etc/systemd/system/stagepi-ui.service" /etc/systemd/system/
install -m 644 "$SOURCE_DIR/etc/systemd/system/ptp4l.service" /etc/systemd/system/

# Enable services
systemctl enable shairport-sync || true
systemctl enable bluetooth || true
systemctl enable stagepi-ui.service || true
systemctl enable stagepi-ble.service || true
systemctl enable ptp4l.service || true

# Reconfigure locales
dpkg-reconfigure locales || true

exit 0
